run:
  timeout: 3m

linters:
  enable:
    - vet
    - errcheck
    - staticcheck
#   - dupl
#   - funlen
#   - goconst
#   - gocritic
    - gofmt
#   - golint
#   - misspell
#   - stylecheck
    - unconvert
#   - whitespace
