version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unconvert
  exclusions:
    rules:
      - linters:
        - errcheck
        source: "^\\s*defer\\s+"

formatters:
  enable:
    - gofmt
