version: 2

env:
  - GO111MODULE=on
  - GOPROXY="https://proxy.golang.org,direct"

archives:
  - id: default
    wrap_in_directory: true

builds:
  - binary: wtfutil
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

before:
  hooks:
    - make install

homebrew_casks:
  - name: wtfutil
    conflicts:
      - formula: wtfutil
    homepage: 'https://wtfutil.com'
    description: 'The personal information dashboard for your terminal.'
    repository:
      owner: wtfutil
      name: homebrew-wtfutil
    hooks:
      post:
        # This hook is needed until this binary is signed and notarized
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtfutil"]
          end
