package nextbus

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/olebedev/config"
)

func TestStrTimeToInt(t *testing.T) {
	tests := []struct {
		name    string
		minutes string
		seconds string
		want    string
	}{
		{"zero values", "0", "0", "00:00"},
		{"whole minutes", "5", "300", "05:00"},
		{"minutes and seconds", "3", "195", "03:15"},
		{"single digit seconds", "1", "65", "01:05"},
		{"large values", "45", "2730", "45:30"},
		{"empty strings default to zero", "", "", "00:00"},
		{"non-numeric defaults to zero", "abc", "xyz", "00:00"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := strTimeToInt(tt.minutes, tt.seconds)
			if got != tt.want {
				t.Errorf("strTimeToInt(%q, %q) = %q, want %q", tt.minutes, tt.seconds, got, tt.want)
			}
		})
	}
}

func TestGetNextBus_ArrayResponse(t *testing.T) {
	response := AutoGenerated{
		Copyright: "test",
		Predictions: Predictions{
			RouteTag:    "N",
			StopTag:     "5678",
			RouteTitle:  "N-Judah",
			AgencyTitle: "SF Muni",
			StopTitle:   "Duboce & Church",
			Direction: Direction{
				Title:         "Outbound",
				PredictionRaw: json.RawMessage(`[{"minutes":"5","seconds":"300","tripTag":"1","isDeparture":"false","block":"1","dirTag":"out","branch":"N","epochTime":"123","vehicle":"v1","affectedByLayover":"false"},{"minutes":"12","seconds":"735","tripTag":"2","isDeparture":"false","block":"2","dirTag":"out","branch":"N","epochTime":"456","vehicle":"v2","affectedByLayover":"false"}]`),
			},
		},
	}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Query().Get("a") != "sf-muni" {
			t.Errorf("expected agency sf-muni, got %s", r.URL.Query().Get("a"))
		}
		if r.URL.Query().Get("r") != "N" {
			t.Errorf("expected route N, got %s", r.URL.Query().Get("r"))
		}
		if r.URL.Query().Get("stopId") != "5678" {
			t.Errorf("expected stopId 5678, got %s", r.URL.Query().Get("stopId"))
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(response)
	}))
	defer server.Close()

	origURL := baseURL
	baseURL = server.URL
	defer func() { baseURL = origURL }()

	result := getNextBus("sf-muni", "N", "5678")

	expected := "N-Judah | ETA [05:00]\nN-Judah | ETA [12:15]\n"
	if result != expected {
		t.Errorf("getNextBus array response:\ngot:  %q\nwant: %q", result, expected)
	}
}

func TestGetNextBus_SingleObjectResponse(t *testing.T) {
	response := AutoGenerated{
		Copyright: "test",
		Predictions: Predictions{
			RouteTag:    "22",
			StopTag:     "1234",
			RouteTitle:  "22-Fillmore",
			AgencyTitle: "SF Muni",
			StopTitle:   "Church & Market",
			Direction: Direction{
				Title:         "Inbound",
				PredictionRaw: json.RawMessage(`{"minutes":"8","seconds":"495","tripTag":"1","isDeparture":"false","block":"1","dirTag":"in","branch":"22","epochTime":"789","vehicle":"v3","affectedByLayover":"true"}`),
			},
		},
	}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(response)
	}))
	defer server.Close()

	origURL := baseURL
	baseURL = server.URL
	defer func() { baseURL = origURL }()

	result := getNextBus("sf-muni", "22", "1234")

	expected := "22-Fillmore | ETA [08:15]\n"
	if result != expected {
		t.Errorf("getNextBus single object response:\ngot:  %q\nwant: %q", result, expected)
	}
}

func TestGetNextBus_HTTPError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Close connection immediately to trigger HTTP error
		hj, ok := w.(http.Hijacker)
		if !ok {
			t.Fatal("server doesn't support hijacking")
		}
		conn, _, _ := hj.Hijack()
		_ = conn.Close()
	}))
	defer server.Close()

	origURL := baseURL
	baseURL = server.URL
	defer func() { baseURL = origURL }()

	result := getNextBus("sf-muni", "N", "1234")
	if result != "[nextbus] error calling umoiq" {
		t.Errorf("expected HTTP error message, got: %q", result)
	}
}

func TestGetNextBus_InvalidJSON(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = fmt.Fprint(w, "not valid json{{{")
	}))
	defer server.Close()

	origURL := baseURL
	baseURL = server.URL
	defer func() { baseURL = origURL }()

	result := getNextBus("sf-muni", "N", "1234")
	if result != "[nextbus] error unmarshalling response body" {
		t.Errorf("expected unmarshal error message, got: %q", result)
	}
}

func TestGetNextBus_InvalidPredictionRaw(t *testing.T) {
	// PredictionRaw is neither a valid object nor array
	response := AutoGenerated{
		Predictions: Predictions{
			RouteTitle: "Test Route",
			Direction: Direction{
				PredictionRaw: json.RawMessage(`"invalid"`),
			},
		},
	}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(response)
	}))
	defer server.Close()

	origURL := baseURL
	baseURL = server.URL
	defer func() { baseURL = origURL }()

	result := getNextBus("sf-muni", "N", "1234")
	// When parseType is empty string (neither "array" nor "object"), falls through to the else branch
	// with zero-value nextBusObject
	expected := "Test Route | ETA [00:00]\n"
	if result != expected {
		t.Errorf("expected fallback formatting, got: %q", result)
	}
}

func TestGetNextBus_EmptyPredictions(t *testing.T) {
	response := AutoGenerated{
		Predictions: Predictions{
			RouteTitle: "N-Judah",
			Direction: Direction{
				PredictionRaw: json.RawMessage(`[]`),
			},
		},
	}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(response)
	}))
	defer server.Close()

	origURL := baseURL
	baseURL = server.URL
	defer func() { baseURL = origURL }()

	result := getNextBus("sf-muni", "N", "1234")
	// Empty array means parseType="array" but no iterations, so empty string
	if result != "" {
		t.Errorf("expected empty string for empty predictions, got: %q", result)
	}
}

func TestGetNextBus_ServerDown(t *testing.T) {
	origURL := baseURL
	baseURL = "http://127.0.0.1:1" // port 1 should refuse connections
	defer func() { baseURL = origURL }()

	result := getNextBus("sf-muni", "N", "1234")
	if result != "[nextbus] error calling umoiq" {
		t.Errorf("expected connection error message, got: %q", result)
	}
}

func TestSettingsDefaults(t *testing.T) {
	if defaultTitle != "nextbus" {
		t.Errorf("expected defaultTitle 'nextbus', got %q", defaultTitle)
	}
	if defaultFocusable != false {
		t.Error("expected defaultFocusable to be false")
	}
}

func TestConfigText(t *testing.T) {
	w := &Widget{settings: &Settings{}}
	text := w.ConfigText()
	if text == "" {
		t.Error("ConfigText() should return non-empty help text")
	}
}

func TestNewSettingsFromYAML(t *testing.T) {
	yamlStr := `
route: "N"
agency: "sf-muni"
stopID: "15678"
enabled: true
position:
  top: 0
  left: 0
  height: 1
  width: 1
refreshInterval: 300
`
	globalStr := `
wtf:
  colors:
    border:
      focusable: "darkslateblue"
      focused: "orange"
      normal: "gray"
`

	yamlConfig, err := config.ParseYaml(yamlStr)
	if err != nil {
		t.Fatalf("failed to parse yaml: %v", err)
	}

	globalConfig, err := config.ParseYaml(globalStr)
	if err != nil {
		t.Fatalf("failed to parse global yaml: %v", err)
	}

	settings := NewSettingsFromYAML("nextbus", yamlConfig, globalConfig)

	if settings.route != "N" {
		t.Errorf("expected route='N', got %q", settings.route)
	}
	if settings.agency != "sf-muni" {
		t.Errorf("expected agency='sf-muni', got %q", settings.agency)
	}
	if settings.stopID != "15678" {
		t.Errorf("expected stopID='15678', got %q", settings.stopID)
	}
	if settings.common == nil {
		t.Error("expected common settings to be non-nil")
	}
}

func TestNewSettingsFromYAML_Defaults(t *testing.T) {
	yamlStr := `
position:
  top: 0
  left: 0
  height: 1
  width: 1
`
	globalStr := `
wtf:
  colors:
    border:
      focusable: "darkslateblue"
      focused: "orange"
      normal: "gray"
`

	yamlConfig, _ := config.ParseYaml(yamlStr)
	globalConfig, _ := config.ParseYaml(globalStr)

	settings := NewSettingsFromYAML("nextbus", yamlConfig, globalConfig)

	if settings.route != "" {
		t.Errorf("expected empty default route, got %q", settings.route)
	}
	if settings.agency != "" {
		t.Errorf("expected empty default agency, got %q", settings.agency)
	}
	if settings.stopID != "" {
		t.Errorf("expected empty default stopID, got %q", settings.stopID)
	}
}
