wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    title: "deepskyblue"
  grid:
    columns: [32, 32, 32, 32, 300]
    rows: [10, 10, 10, 10, 10, 300]
  refreshInterval: 1
  mods:
    example_pluggable:
      title: "¯\\_(ツ)_/¯"
      enabled: true
      plugin:
        path: "./pluggable/example_pluggable/example_pluggable"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
